
#ifndef ERROR_H
#define ERROR_H


typedef  enum _MP_ERROR 
{
  MPERR_NO_ERROR=0,
  MPERR_STILL_INSTANCE,
  MPERR_TYPE_NOT_FIND,
  MPERR_CANNOT_LOAD_PLUG,
  MPERR_NO_INSTANCE_TO_DESTROY,
  MPERR_CANNOT_CREATE_ASSO,
  MPERR_CANNOT_ADD_PLUG,
  MPERR_CANNOT_DESTROY_PLUG,
  MPERR_CANNOT_DEL_INST,
  MPERR_NO_INST,
  MPERR_NO_SET, 
  MPERR_NB_INST,
  MPERR_NO_ACCESS,
  MPERR_ERROR,
  MPERR_NO_ASSO,
  MPERR_NO_MEMORY_TO_FREE,
  MPERR_MEMORY_NOT_FIND


}MP_ERROR;


#endif 
