#! /bin/sh
#
# set environnement
#
# called from mMosaic with argument : -windowId nnnn Applet
#	nnnn is the window ID
#	Applet is the Applet.class file
#

echo $*

CLASSPATH=/sig/tomcat/dauphin/biss/lib:.:/usr/local/share/kaffe/classes.zip
KAFFEHOME=/usr/local/share/kaffe
LD_LIBRARY_PATH=/sig/tomcat/dauphin/mbone-dev/biss-0.87/src/biss/awt/kernel/X:/usr/local/lib

if [ ! -d "$HOME/.mMosaic" ] ; then
    echo "Creating $HOME/.mMosaic directory"
    /usr/bin/mkdir -p $HOME/.mMosaic
fi

if [ ! -d "$HOME/.mMosaic/classes" ] ; then
    echo "Creating $HOME/.mMosaic/classes directory"
    /usr/bin/mkdir -p $HOME/.mMosaic/classes
fi

CLASSPATH=${CLASSPATH}:${HOME}/.mMosaic/classes/$3.zip

export CLASSPATH KAFFEHOME LD_LIBRARY_PATH

echo $CLASSPATH

wid=`echo $1 $2`
applet=$3
shift
shift
shift


cd ${HOME}/.mMosaic/classes
unzip -o $applet.zip


echo eval exec /usr/local/bin/kaffe -Dawt.toolkit=biss.awt.kernel.Toolkit biss.awt.AppletViewer $wid $applet $*
eval exec /usr/local/bin/kaffe -Dawt.toolkit=biss.awt.kernel.Toolkit biss.awt.AppletViewer $wid $applet $*

