#! /bin/sh
#
# 7/06/2000: G.Dauphin 
#

#echo @$0 @$1 @$2 @$3
#echo $*
#sleep 60

case $1 in
	-windowId)
		OPT="-w"
		shift
		OPT="${OPT}$1"
		shift
		;;
	*)
		echo usage: gifview -windowID xwid option...
		exit 1
		;;
esac

tmp=/tmp/mMosaic.$$.wget

/usr/local/bin/wget -O $tmp $1

#echo "/usr/local/bin/mtvp $OPT $*"
#exec /usr/local/bin/gifview $OPT $*

exec /usr/local/bin/gifview -a $OPT $tmp ; rm $tmp
