#!/bin/sh
set -v
ST=60

PID=$1

while true
do

cat << EOF >/tmp/Mosaic.$PID
goto
p3-o.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-r1.html
EOF
kill -USR1 $PID
sleep $ST



cat << EOF >/tmp/Mosaic.$PID
goto
p3-l1.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-b1.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-c1.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-c1-0.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-c1-1.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-c1-2.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-c1-3.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-c1-4.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-c1-5.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
p3-c1-6.html
EOF
kill -USR1 $PID
sleep $ST

cat << EOF >/tmp/Mosaic.$PID
goto
photo.html
EOF
kill -USR1 $PID
sleep 120


done
