#! /bin/sh
#
# 7/06/2000: G.Dauphin 
#

#echo @$0 @$1 @$2 @$3
#echo $*
#sleep 60

case $1 in
	-windowId)
		OPT="-W"
		shift
		OPT="${OPT}$1"
		shift
		;;
	*)
		echo usage: mtvp -windowID xwid option...
		exit 1
		;;
esac

 
#for pseudo 8bit set this 
MTVP_8BIT_MIN_COLORS=32
export MTVP_8BIT_MIN_COLORS
MTVP_8BIT_MAX_COLORS=33
export MTVP_8BIT_MAX_COLORS

#echo "/usr/local/bin/mtvp $OPT $*"

exec /usr/local/bin/mtvp $OPT $*
