/* Please read copyright.ncsa. Don't remove next line */
#include "../Copyrights/copyright.ncsa"

#ifndef __PIXMAPS_H__               
#define __PIXMAPS_H__ 

#include "pixmaps/icon.1.xpm"
#include "pixmaps/icon.2.xpm"
#include "pixmaps/icon.3.xpm"
#include "pixmaps/icon.4.xpm"
#include "pixmaps/icon.5.xpm"
#include "pixmaps/icon.6.xpm"
#include "pixmaps/icon.7.xpm"
#include "pixmaps/icon.8.xpm"
#include "pixmaps/icon.9.xpm"
#include "pixmaps/icon.10.xpm"
#include "pixmaps/icon.11.xpm"
#include "pixmaps/icon.12.xpm"
#include "pixmaps/icon.13.xpm"
#include "pixmaps/icon.14.xpm"
#include "pixmaps/icon.15.xpm"
#include "pixmaps/icon.16.xpm"
#include "pixmaps/icon.17.xpm"
#include "pixmaps/icon.18.xpm"
#include "pixmaps/icon.19.xpm"
#include "pixmaps/icon.20.xpm"
#include "pixmaps/icon.21.xpm"
#include "pixmaps/icon.22.xpm"
#include "pixmaps/icon.23.xpm"
#include "pixmaps/icon.24.xpm"
#include "pixmaps/icon.25.xpm"

#include "pixmaps/s_icon.1.xpm"
#include "pixmaps/s_icon.2.xpm"
#include "pixmaps/s_icon.3.xpm"
#include "pixmaps/s_icon.4.xpm"
#include "pixmaps/s_icon.5.xpm"
#include "pixmaps/s_icon.6.xpm"
#include "pixmaps/s_icon.7.xpm"
#include "pixmaps/s_icon.8.xpm"
#include "pixmaps/s_icon.9.xpm"
#include "pixmaps/s_icon.10.xpm"
#include "pixmaps/s_icon.11.xpm"
#include "pixmaps/s_icon.12.xpm"
#include "pixmaps/s_icon.13.xpm"
#include "pixmaps/s_icon.14.xpm"
#include "pixmaps/s_icon.15.xpm"
#include "pixmaps/s_icon.16.xpm"
#include "pixmaps/s_icon.17.xpm"
#include "pixmaps/s_icon.18.xpm"
#include "pixmaps/s_icon.19.xpm"
#include "pixmaps/s_icon.20.xpm"
#include "pixmaps/s_icon.21.xpm"
#include "pixmaps/s_icon.22.xpm"
#include "pixmaps/s_icon.23.xpm"
#include "pixmaps/s_icon.24.xpm"
#include "pixmaps/s_icon.25.xpm"

#include "pixmaps/unlock_none.xpm"
#include "pixmaps/unlock_unknown.xpm"
#include "pixmaps/lock_md5.xpm"
#include "pixmaps/lock_kerberos4.xpm"
#include "pixmaps/lock_kerberos5.xpm"
#include "pixmaps/lock_basic.xpm"
#include "pixmaps/lock_domain.xpm"
#include "pixmaps/lock_login.xpm"

#include "pixmaps/toolbar_save_1.xpm"
#include "pixmaps/toolbar_ftp_put_1.xpm"
#include "pixmaps/toolbar_ftp_mkdir_1.xpm"
#include "pixmaps/toolbar_back_1.xpm"
#include "pixmaps/toolbar_forw_1.xpm"
#include "pixmaps/toolbar_open_1.xpm"
#include "pixmaps/toolbar_reload_1.xpm"
#include "pixmaps/toolbar_print_1.xpm"
#include "pixmaps/toolbar_news_list_1.xpm"
#include "pixmaps/toolbar_news_groups_1.xpm"
#include "pixmaps/toolbar_search_1.xpm"
#include "pixmaps/toolbar_home_1.xpm"
#include "pixmaps/toolbar_post_1.xpm"
#include "pixmaps/toolbar_followup_1.xpm"
#include "pixmaps/toolbar_next_art_1.xpm"
#include "pixmaps/toolbar_next_thr_1.xpm"
#include "pixmaps/toolbar_prev_art_1.xpm"
#include "pixmaps/toolbar_prev_thr_1.xpm"
#include "pixmaps/toolbar_open_window_1.xpm"
#include "pixmaps/toolbar_clone_window_1.xpm"
#include "pixmaps/toolbar_close_window_1.xpm"
#include "pixmaps/toolbar_hotlist_1.xpm"

#include "pixmaps/tearv.xpm"
#include "pixmaps/tearh.xpm"

#include "pixmaps/not_secure.xpm"

extern void MakePixmaps(Widget wid);

#endif
